global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'system-monitor'
    metrics_path: '/metrics/prometheus'
    static_configs:
      # CHANGED: We now point to port 8000 because that is where your app is listening
      - targets: ['system-monitor:8000']